# Generated by Django 3.2.6 on 2021-12-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ott',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ott', models.CharField(choices=[('Watcha', 'Watcha'), ('Netflix', 'Netflix'), ('Tving', 'Tving'), (
                    'Youtube', 'Youtube'), ('Disney', 'Disney'), ('Coupangplay', 'Coupangplay'), ('Wavve', 'Wavve')], max_length=15)),
                ('membership', models.CharField(choices=[
                 ('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=10)),
                ('max_people', models.IntegerField(default=1)),
                ('cost', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='public/img')),
            ],
        ),
    ]
