# Generated by Django 3.2.6 on 2021-12-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0002_alter_ott_ott'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ott',
            name='ott',
            field=models.CharField(choices=[('Watcha', 'Watcha'), ('Netflix', 'Netflix'), ('Tving', 'Tving'), (
                'Youtube', 'Youtube'), ('Disney', 'Disney'), ('Coupangplay', 'Coupangplay'), ('Wavve', 'Wavve')], max_length=15),
        ),
    ]
