version: "3.1"
services:
  db:
    image: mysql:8.0.22
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: subroker
      MYSQL_USER: root
      MYSQL_PASSWORD: swppteam8
      MYSQL_ROOT_PASSWORD: swppteam8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
