# Generated by Django 3.2.6 on 2021-12-03 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_cnt', models.IntegerField(default=0)),
                ('favorite_users', models.ManyToManyField(blank=True, related_name='favorite_contents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
