# Generated by Django 3.2.8 on 2021-12-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='director',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='content',
            name='ott',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='content',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='content',
            name='poster',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='content',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='content',
            name='release_date',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='content',
            name='cast',
            field=models.ManyToManyField(blank=True, to='content.Actor'),
        ),
        migrations.AddField(
            model_name='content',
            name='genres',
            field=models.ManyToManyField(blank=True, to='content.Genre'),
        ),
    ]
