# Generated by Django 3.2.6 on 2021-12-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('create', 'create'), ('join', 'join'), ('quit', 'quit'), ('delete', 'delete')], default='create', max_length=10),
        ),
    ]
