# Generated by Django 3.1.3 on 2021-11-18 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_cnt', models.IntegerField(default=0)),
                ('favorite_users', models.ManyToManyField(blank=True, related_name='favorite_contents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ott',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ott', models.CharField(choices=[('Watcha', 'Watcha'), ('Netflix', 'Netflix'), ('Tving', 'Tving'), ('Youtube', 'Youtube'), ('Disney', 'Disney'), ('CoupangPlay', 'CoupangPlay'), ('Wavve', 'Wavve')], max_length=15)),
                ('membership', models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=10)),
                ('max_people', models.IntegerField(default=1)),
                ('cost', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='ott_image')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reviews', to='subroker.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Group', max_length=64)),
                ('description', models.TextField(default='')),
                ('is_public', models.BooleanField(default=True)),
                ('password', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('will_be_deleted', models.BooleanField(default=False)),
                ('payday', models.IntegerField(default=1)),
                ('account_bank', models.CharField(choices=[('NongHyup', 'NongHyup'), ('KookMin', 'KookMin'), ('KakaoBank', 'KakaoBank'), ('ShinHan', 'ShinHan'), ('Woori', 'Woori'), ('IBK', 'IBK'), ('Hana', 'Hana'), ('Saemaeul', 'Saemaeul'), ('DaegooBank', 'DaegooBank'), ('PostOffice', 'PostOffice'), ('Toss', 'Toss'), ('CitiBank', 'CitiBank'), ('KDB', 'KDB')], max_length=15)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=30)),
                ('current_people', models.IntegerField(default=1)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_leader', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='user_groups', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_groups', to='subroker.ott')),
            ],
        ),
    ]
