# Generated by Django 3.2.6 on 2021-11-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subroker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
