# Generated by Django 3.2.7 on 2021-11-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subroker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ott',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ott',
            name='max_people',
            field=models.IntegerField(default=1),
        ),
    ]
