# Generated by Django 3.2.7 on 2021-11-06 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subroker', '0002_auto_20211106_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Group', max_length=64)),
                ('description', models.TextField(default='')),
                ('is_public', models.BooleanField(default=True)),
                ('password', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('will_be_deleted', models.BooleanField(default=False)),
                ('ott', models.CharField(choices=[('Watcha', 'Watcha'), ('Netflix', 'Netflix'), ('Tving', 'Tving'), ('Youtube', 'Youtube'), ('Disney', 'Disney'), ('CoupangPlay', 'CoupangPlay'), ('Wavve', 'Wavve')], max_length=15)),
                ('payday', models.IntegerField(default=1)),
                ('account_bank', models.CharField(choices=[('NH', 'NongHyup'), ('KB', 'KookMin'), ('KAKAO', 'Kakao'), ('SH', 'ShinHan'), ('WR', 'Woori'), ('IBK', 'IBK'), ('HN', 'Hana'), ('SM', 'Saemaeul'), ('DGB', 'Daegoo Bank'), ('POST', 'PostOffice'), ('TOSS', 'Toss'), ('CITI', 'CitiBank'), ('KDB', 'KDB')], max_length=5)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=30)),
                ('current_people', models.IntegerField(default=1)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_set', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_set', to='subroker.ott')),
            ],
        ),
    ]
