# Generated by Django 3.2.7 on 2021-11-06 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subroker', '0004_content_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='user_id',
            field=models.ManyToManyField(blank=True, related_name='like_users_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
